### PR TITLE
Refactoring base monitor to a finite state machine

### PR DESCRIPTION
**Pull request by jessedearing**
- Reduces cyclomatic complexity
- Ties events to state transitions
- De-dupes resolves

### CODE REVIEW

**Comment by dselans** [comment]
This is super nice @jessedearing 

Is it ready? If so, maybe we can do a quick zoom and walk through how the entire thing works (I haven't fully looked through the PR yet)?

**Comment by jessedearing** [comment]
Yep. It's ready to go. Let's go over it at your leisure

**Comment by dselans** [comment]
Cool, I'll find some time tonight and work through the PR to understand what's going on. If anything doesn't make sense, I'll ping you.

**Comment by dselans** [comment]
Oh, one minor note - since you already did the heavy lifting of thoroughly testing this, one missed test case that I noticed is that we do not check for an invalid `transitionStateTo`. Trivial to add, just figured I'd make a note of it.

**Comment by jessedearing** [comment]
1. Instead of passing in functions to a map, we could just pass the messages and when a state changes we could update the message. When we transition to an `OK` state then we just go through and send the resolve messages and delete them from the map. Since we have to copy the message object anyway this seems like it make more sense anyway.
2. If we do just put the message into the map then updating the attempted count seems easy enough.
3. `transitionStateTo` - I was looking at this when it was looking at the code coverage for the tests. As it turns out there is not _currently_ a condition that will cause a transition to fail. Following that it seems like there's not a condition that would cause `handle` to error either so we could remove the extra error checking for those too.

**Comment by dselans** [comment]
@jessedearing I can't fully see what your suggested way would look like, but it sounds like it makes sense. Can you push an updated PR? If it allows for a simpler way to adjust the outbound resolve messages, that's even better - we can make it more obvious that something is now recovered (this really only pertains to alerters that are chat-related).

Re 3: I'd probably keep it. It would clean it up, but the fact that the methods currently return errors make them a bit easier to unit test individually as well. I can also see this as a way to potentially prevent someone from doing something funky inside of `handle` and inadvertently passing a state that doesn't exist. Ie. introducing a new alert state and things bomb because state `3` isn't actually defined.

**Comment by jessedearing** [comment]
@dselans Just pushed up an update.

Basically just use a `map[string]*alerter.Message` type for the resolve messages and then send those messages on transition to the OK state.

**Comment by dselans** [comment]
Jesse, this is super solid.

Thanks for doing this.

**Pull request merged**
